
package taskmeter.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TaskmeterService", targetNamespace = "http://ws.taskmeter/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TaskmeterService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "synchronize", targetNamespace = "http://ws.taskmeter/", className = "taskmeter.ws.Synchronize")
    @ResponseWrapper(localName = "synchronizeResponse", targetNamespace = "http://ws.taskmeter/", className = "taskmeter.ws.SynchronizeResponse")
    @Action(input = "http://ws.taskmeter/TaskmeterService/synchronizeRequest", output = "http://ws.taskmeter/TaskmeterService/synchronizeResponse")
    public List<Integer> synchronize(
        @WebParam(name = "arg0", targetNamespace = "")
        List<WorkingSlot> arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://ws.taskmeter/", className = "taskmeter.ws.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://ws.taskmeter/", className = "taskmeter.ws.LoginResponse")
    @Action(input = "http://ws.taskmeter/TaskmeterService/loginRequest", output = "http://ws.taskmeter/TaskmeterService/loginResponse")
    public int login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<taskmeter.ws.Project>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listProjects", targetNamespace = "http://ws.taskmeter/", className = "taskmeter.ws.ListProjects")
    @ResponseWrapper(localName = "listProjectsResponse", targetNamespace = "http://ws.taskmeter/", className = "taskmeter.ws.ListProjectsResponse")
    @Action(input = "http://ws.taskmeter/TaskmeterService/listProjectsRequest", output = "http://ws.taskmeter/TaskmeterService/listProjectsResponse")
    public List<Project> listProjects(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
