
package taskmeter.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TaskmeterWS", targetNamespace = "http://ws.taskmeter/", wsdlLocation = "http://localhost:8080/backend/TaskmeterWS?wsdl")
public class TaskmeterWS
    extends Service
{

    private final static URL TASKMETERWS_WSDL_LOCATION;
    private final static WebServiceException TASKMETERWS_EXCEPTION;
    private final static QName TASKMETERWS_QNAME = new QName("http://ws.taskmeter/", "TaskmeterWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/backend/TaskmeterWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TASKMETERWS_WSDL_LOCATION = url;
        TASKMETERWS_EXCEPTION = e;
    }

    public TaskmeterWS() {
        super(__getWsdlLocation(), TASKMETERWS_QNAME);
    }

    public TaskmeterWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), TASKMETERWS_QNAME, features);
    }

    public TaskmeterWS(URL wsdlLocation) {
        super(wsdlLocation, TASKMETERWS_QNAME);
    }

    public TaskmeterWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TASKMETERWS_QNAME, features);
    }

    public TaskmeterWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaskmeterWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TaskmeterService
     */
    @WebEndpoint(name = "TaskmeterServicePort")
    public TaskmeterService getTaskmeterServicePort() {
        return super.getPort(new QName("http://ws.taskmeter/", "TaskmeterServicePort"), TaskmeterService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaskmeterService
     */
    @WebEndpoint(name = "TaskmeterServicePort")
    public TaskmeterService getTaskmeterServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.taskmeter/", "TaskmeterServicePort"), TaskmeterService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TASKMETERWS_EXCEPTION!= null) {
            throw TASKMETERWS_EXCEPTION;
        }
        return TASKMETERWS_WSDL_LOCATION;
    }

}
